//JUDUL
INDOMIE GORENG TELUR

#include <iostream>
using namespace std;

//KAMUS
INDOMIE GORENG “MIE SEDAP” 1 BUNGKUS
TELUR AYAM MENTAH 1 BUAH
SAWI 2 HELAI
AIR 1 LITER
CABE SETAN 2
BAWANG MERAH 3 SIUNG

//DISKRIPSI
AMBIL BAWAH 3 SIUNG
WHILE (MASIH ADA BAWAH YANG BELUM TERKUPAS) do
	AMBIL 1 BAWAH
	KUPAS BAWANG MERAH

AMBIL BAWAH 3 SIUNG
WHILE (MASIH ADA BAWAH YANG BELUM TERIRIS) do
	AMBIL 1 BAWANG TERKUPAS
	POTONG TIPIS KUPAS BAWANG MERAH


POSISIKAN WAJAN DIATAS KOMPOR
TUANGKAN MINYSK GORENG 250 MILI
NYALAKAN KOMPOR
if MINYAK GORENG SUDAH PANAS THEN
	{
	TUANGKAN BAWANG MERAH IRIS KE MEJA TSB
	ADUK TUNGGU SESAAT HINGGA WARNA KECOKLATAN
	MATIKAN KOMPOR
	ANGKAT BAWANG MERAH IRIS GORENG & TIRISKAN
}

else
{ TUNGGU SAMPAI MINYAK GORENG PANAS }

TUANGKAN MINYAK GORENG DARI WAJAN KE TEMPT MINYAK GORENG
TUANGKAN AIR SECUKUPNYA KE DALAM WAJAN 500 MILI
HIDUPKAN KOMPOR
TUNGGU SAMPAI AIR MENDIDIH
PECAHKAN 1 TELUR DAN TUANG ISI TELUR KE DALAM AIR MENDIDIH
TUNGGU 10 MENIT MENJADI TELUR REBUS
BILA SUDAH ANGKAT DAN TIRISKAN
BUKA INDOMIE GORENG MIE SEDAP
TUANGKAN ISI MIE KEMASAN TERSEBUT KEDALAM AIR PANAS DI ATAS WAJAN
WHILE (MIE SUDAH MELUNAK) do
{
	ANGKAT
	TIRISKAN
}

AMBIL PIRING
TUANGKAN MIE LUNAK DIATAS PIRING / MANGKOK
BUKA BUMBU PELENGKAP DAN TUANGKAN DAN ADUK MERATA
IF (RASA MIE GORENG BELUM SESUAI) THEN
	{
		TAMBAH KECAP
		TAMBAH MECIN DLL
	}

TUANGKAN TELUR REBUS, BAWANG MERAH GORENG &
DIATAS MIE YANG SUDAH BERBUMBU